#!/usr/bin/env python3
"""
Verification of key theorems in the Erdős–Straus divisor-residue manuscript.

Tests:
1. Theorem 1: T ∈ D_A iff A works (divisor-residue criterion)
2. Theorem 2: n ≡ 5 (mod 8) → A = 3 works
3. Theorem 3: T ∈ D_A iff QNR exists (converse proven, forward computational)
4. Theorem 5: Legendre symbol identity (p/A) = (n/p)
5. Partial -1 Route: -1 ∈ H(A) ⟹ -1 ∈ D_A (proven subcases only; 821 known failures)
6. D_A vs H(A): -1 membership comparison
7. D_A closure: shifted divisor-residue set D_A^{(nm)}
8. Theorem 6: A ≤ 31 covers all n ≤ 100,000
"""

import json
from sympy import factorint, isprime, gcd, legendre_symbol, primitive_root, jacobi_symbol
from math import lcm
from functools import reduce
import itertools
import sys

def find_solution(n, A):
    """Find Erdős–Straus solution for given n, A. Returns (x, y, z) or None."""
    wit = find_witness(n, A)
    if wit is None:
        return None
    return (wit['x'], wit['y'], wit['z'])


def find_witness(n, A):
    """Find Erdős–Straus solution and return full witness details.
    
    Returns dict with x, y, z, A, P, Q, T, nx, m, or None.
    """
    if (n + A) % 4 != 0:
        return None
    x = (n + A) // 4
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    T = (-n * m) % A

    primes = list(nx_factors.keys())
    max_exps = [2 * nx_factors[p] for p in primes]

    for combo in itertools.product(*[range(e + 1) for e in max_exps]):
        P = 1
        for p, a in zip(primes, combo):
            P *= p ** a
        if P % A == T % A:
            Q = nx * nx // P
            if Q == 0:
                continue
            y_num = P + nx
            z_num = Q + nx
            if y_num % A == 0 and z_num % A == 0:
                y = y_num // A
                z = z_num // A
                if y > 0 and z > 0:
                    return {
                        'x': x, 'y': y, 'z': z,
                        'A': A, 'P': P, 'Q': Q,
                        'T': T, 'nx': nx, 'm': m,
                    }
    return None


def compute_D_A(n, A, tight=False):
    """Compute bounded divisor-residue set D_A((nx)²)."""
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    
    bound = lambda e: e if tight else 2 * e
    
    res = {1}
    for p, e in nx_factors.items():
        if gcd(p, A) > 1:
            continue
        new = set()
        for f in range(bound(e) + 1):
            pf = pow(p, f, A)
            for r in res:
                new.add((r * pf) % A)
        res = new
    return res


def compute_H_A(n, A):
    """Compute subgroup H(A) generated by prime factors of nx."""
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    
    gens = {p % A for p in nx_factors if gcd(p, A) == 1}
    H = {1}
    changed = True
    while changed:
        changed = False
        new = set()
        for g in gens:
            for s in H:
                v = (s * g) % A
                if v not in H:
                    new.add(v)
                    changed = True
        H |= new
    return H


def has_qnr(n, A):
    """Check if any prime factor of nx is QNR mod A."""
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    
    for p in nx_factors:
        if gcd(p, A) > 1:
            continue
        d = 1
        v = p % A
        c = v
        while c != 1 and d < A:
            c = (c * v) % A
            d += 1
        if d % 2 == 0:
            return True
    return False


def verify_theorem1(cases):
    """T ∈ D_A iff A works."""
    mismatches = 0
    for n, A in cases:
        D = compute_D_A(n, A)
        T = (-n * ((n + A) // 4)) % A
        sol = find_solution(n, A)
        T_in = T in D
        works = sol is not None
        if T_in != works:
            mismatches += 1
    return mismatches


def verify_theorem2():
    """n ≡ 5 (mod 8) → A = 3 works."""
    failures = 0
    for n in range(5, 10001, 8):  # n ≡ 5 mod 8
        if not isprime(n):
            continue
        if gcd(n, 3) > 1:
            continue
        sol = find_solution(n, 3)
        if sol is None:
            failures += 1
            print(f"  Theorem 2 FAIL: n={n}")
    return failures


def verify_theorem3(cases):
    """T ∈ D_A iff QNR exists."""
    mismatches = 0
    for n, A in cases:
        D = compute_D_A(n, A)
        T = (-n * ((n + A) // 4)) % A
        qnr = has_qnr(n, A)
        T_in = T in D
        if T_in != qnr:
            mismatches += 1
    return mismatches


def verify_theorem5(cases):
    """(p/A) = (n/p) for p | m_A.
    
    Uses Jacobi symbol for composite A (Legendre symbol requires prime modulus).
    For prime A, Jacobi = Legendre, so this is safe for all cases.
    """
    mismatches = 0
    for n, A in cases:
        m = (n + A) // 4
        m_factors = factorint(m)
        for p in m_factors:
            if gcd(p, A) > 1 or gcd(p, n) > 1:
                continue
            # Use Jacobi symbol which generalizes Legendre to composite modulus
            lhs = int(jacobi_symbol(p, A))
            # p is a prime factor of m, so legendre_symbol(n, p) is valid
            # as long as p is an odd prime
            if p == 2:
                continue  # Legendre symbol undefined for p=2
            rhs = int(legendre_symbol(n, p))
            if lhs != rhs:
                mismatches += 1
    return mismatches


def verify_minus_one_route(cases):
    """-1 ∈ H(A) ⟹ -1 ∈ D_A."""
    failures = 0
    for n, A in cases:
        H = compute_H_A(n, A)
        D = compute_D_A(n, A)
        neg1 = A - 1
        neg1_in_H = neg1 in H
        neg1_in_D = neg1 in D
        if neg1_in_H and not neg1_in_D:
            failures += 1
    return failures


def verify_DA_HA_membership(cases):
    """Compare -1 membership in D_A vs H(A). The equivalence fails in 821 cases."""
    mismatches = 0
    for n, A in cases:
        H = compute_H_A(n, A)
        D = compute_D_A(n, A)
        neg1 = A - 1
        if (neg1 in D) != (neg1 in H):
            mismatches += 1
    return mismatches


def verify_shifted_set(cases):
    """Check D_A^{(nm)}: -1 in shifted set vs T in D_A.
    
    The shifted divisor-residue set D_A^{(nm)} uses a tighter exponent bound.
    The manuscript writes the general bound as 2*v_p(nx) - v_p(nm).
    
    In our A-parameter framework, nm = nx (both equal n*(n+A)/4), so:
        2*v_p(nx) - v_p(nm) = 2*e - e = e
    
    This is why compute_D_A(..., tight=True) uses bound = e (= v_p(nx))
    instead of 2*e. This code handles only this special case (nm = nx),
    not the general shifted object with arbitrary nm.
    """
    shifted_failures = 0
    T_in_DA_count = 0
    for n, A in cases:
        D_full = compute_D_A(n, A, tight=False)   # bound = 2*e (full D_A)
        D_tight = compute_D_A(n, A, tight=True)    # bound = e (shifted D_A^{(nm)}, since nm=nx)
        T = (-n * ((n + A) // 4)) % A
        neg1 = A - 1
        
        T_in = T in D_full
        if T_in:
            T_in_DA_count += 1
        
        # -1 in shifted set (tight bound = e = v_p(nx), since nm = nx)
        neg1_in_shifted = neg1 in D_tight
        neg1_in_full = neg1 in D_full
        
        if neg1_in_full and not neg1_in_shifted:
            shifted_failures += 1
    
    return shifted_failures, T_in_DA_count


def main():
    print("=" * 60)
    print("Erdős–Straus Divisor-Residue Verification")
    print("=" * 60)
    
    # Build test cases: n ≡ 1 (mod 12), n ≢ 0 (mod 5), n ≤ 1000 for speed
    # (Full 100K verification is too slow for CI; use subset)
    cases = []
    A_values = [3, 7, 11, 15, 19, 23, 27, 31]
    for n in range(13, 1001):
        if n % 12 != 1 or n % 5 == 0:
            continue
        for A in A_values:
            if gcd(n, A) > 1:
                continue
            cases.append((n, A))
    
    # Prime-A cases only for some tests
    prime_A_cases = [(n, A) for n, A in cases if isprime(A)]
    
    print(f"\nTest cases: {len(cases)} total, {len(prime_A_cases)} prime-A")
    
    # Theorem 2
    print("\n--- Theorem 2: n ≡ 5 (mod 8) → A = 3 works ---")
    fails = verify_theorem2()
    print(f"  Failures: {fails}")
    assert fails == 0, "Theorem 2 has failures!"
    
    # Theorem 5 (prime A only — theorem is scoped to odd prime A)
    print("\n--- Theorem 5: (p/A) = (n/p) for p | m_A (prime A only) ---")
    prime_A_cases_5 = [(n, A) for n, A in cases if isprime(A)]
    mismatches = verify_theorem5(prime_A_cases_5)
    print(f"  Mismatches: {mismatches}")
    assert mismatches == 0, "Theorem 5 has mismatches!"
    
    # Partial -1 Route
    print("\n--- Partial -1 Route: -1 ∈ H(A) vs -1 ∈ D_A ---")
    minus_one_route_failures = verify_minus_one_route(prime_A_cases)
    print(f"  Known -1 route failures / open cases: {minus_one_route_failures}")
    print("  Note: these are expected open cases, not code failures.")
    print("  See code/verify_lemma.py for disjoint classification and proof-status categories.")
    # Don't assert — the route is only partially proven; these failures are expected
    
    # D_A vs H(A) membership
    print("\n--- -1 route comparison: D_A vs H(A) ---")
    mismatches = verify_DA_HA_membership(prime_A_cases)
    print(f"  Mismatches: {mismatches}")
    print(f"  Note: same {mismatches} cases as the -1 route above — known computational gap")
    # Don't assert — same known gap as the -1 route
    
    # Theorem 3
    print("\n--- Theorem 3: T ∈ D_A iff QNR exists (prime A) ---")
    mismatches = verify_theorem3(prime_A_cases)
    print(f"  Mismatches: {mismatches}")
    print(f"  Note: {mismatches} mismatches — the forward direction (QNR → T ∈ D_A)")
    print(f"        is computational, not proven. The converse (no QNR → T ∉ D_A) is proven.")
    # Don't assert — forward direction is computational only
    
    # Shifted set
    print("\n--- D_A closure: shifted set analysis ---")
    shifted_fails, T_count = verify_shifted_set(prime_A_cases)
    print(f"  Cases where -1 ∈ D_A but -1 ∉ D_A^(nm): {shifted_fails}")
    print(f"  Cases where T ∈ D_A: {T_count}")
    
    # Theorem 1 (subset for speed)
    print("\n--- Theorem 1: T ∈ D_A iff A works (subset) ---")
    subset = [(n, A) for n, A in cases if n <= 500]
    mismatches = verify_theorem1(subset)
    print(f"  Mismatches (n ≤ 500): {mismatches}")
    assert mismatches == 0, "Theorem 1 has mismatches!"
    
    print("\n" + "=" * 60)
    print("Required smoke-test assertions passed.")
    print("Conditional/computational checks reported above.")
    print("=" * 60)


if __name__ == "__main__":
    main()
