#!/usr/bin/env python3
"""
Centered Divisor-Residue Set Analysis for the Erdős–Straus Lemma.

For each prime n ≤ 100,000 with n ≡ 1 (mod 12), n ≢ 0 (mod 5), and each
prime A ∈ {3, 7, 11, 19, 23, 31} with gcd(n,A)=1:

1. Compute N = n*(n+A)/4, factorize N
2. Compute H(A) = subgroup generated by prime factors of N mod A
3. Find generator u of H(A)
4. Build dlog table: dlog[x] = j where u^j ≡ x (mod A)
5. Compute true dlog coordinates s_i = dlog[p_i % A]
6. Compute centered sumset Σ_A(N) = {Σ s_i*δ_i mod h : -e_i ≤ δ_i ≤ e_i}
7. Check whether h/2 ∈ Σ_A(N) (centered criterion)
8. Check whether T = -N mod A is in D_A(N²) (original criterion)
9. Verify they match: T ∈ D_A iff h/2 ∈ Σ_A(N)
10. Find shortest signed representation of h/2
11. Classify each case

For the 821 lemma-failure cases (where -1 ∉ D_A), compute the actual
working divisor P that achieves T ∈ D_A, then compute δ_i = α_i - e_i.
"""

import json
import sys
import os
from math import gcd, lcm
from functools import reduce
from itertools import product as iterproduct
from collections import Counter

from sympy import factorint, isprime


# ── Core functions ─────────────────────────────────────────────────────────

def compute_H_A_from_factors(nx_factors, A):
    """Compute subgroup H(A) generated by prime factors of N mod A."""
    gens = {p % A for p in nx_factors if gcd(p, A) == 1}
    H = {1}
    changed = True
    while changed:
        changed = False
        new = set()
        for g in gens:
            for s in H:
                v = (s * g) % A
                if v not in H:
                    new.add(v)
                    changed = True
        H |= new
    return H


def subgroup_generator(A, H):
    """Find a generator u of H(A) with multiplicative order = |H(A)|."""
    h = len(H)
    if h == 1:
        return 1
    for u in sorted(H):
        if u == 1:
            continue
        seen = {1}
        cur = u
        while cur not in seen:
            seen.add(cur)
            cur = (cur * u) % A
        if len(seen) == h:
            return u
    return 1  # Should not reach here for non-trivial H


def dlog_table(A, u, h):
    """Build discrete log table: dlog[x] = j where u^j ≡ x (mod A)."""
    table = {}
    cur = 1
    for j in range(h):
        table[cur] = j
        cur = (cur * u) % A
    return table


def compute_D_A(n, A, nx_factors):
    """Compute bounded divisor-residue set D_A(N²) with bound 2*e_i."""
    res = {1}
    for p, e in nx_factors.items():
        if gcd(p, A) > 1:
            continue
        new = set()
        for f in range(2 * e + 1):
            pf = pow(p, f, A)
            for r in res:
                new.add((r * pf) % A)
        res = new
    return res


def compute_centered_sumset(dlog_coords, exponents, h):
    """Compute Σ_A(N) = {Σ s_i*δ_i mod h : -e_i ≤ δ_i ≤ e_i}.
    
    Uses iterative set building to handle potentially large sets.
    """
    result = {0}
    for s_i, e_i in zip(dlog_coords, exponents):
        new = set()
        for delta in range(-e_i, e_i + 1):
            shift = (delta * s_i) % h
            for r in result:
                new.add((r + shift) % h)
        result = new
    return result


def compute_stabilizer(S, m):
    """Compute the additive stabilizer of S in Z/mZ.
    
    stab(S) = {t ∈ Z/mZ : S + t = S}
    """
    if not S:
        return {0}
    stab = {0}
    for t in range(1, m):
        if all((s + t) % m in S for s in S):
            stab.add(t)
    return stab


def find_witness_for_residue(nx_factors, A, target_res, bound_func):
    """Find exponents a_i (0 ≤ a_i ≤ bound_func(e_i)) such that
    ∏ p_i^{a_i} ≡ target_res (mod A).
    Returns dict {p: a_i} or None.
    """
    primes = [p for p in nx_factors if gcd(p, A) == 1]
    exps = [nx_factors[p] for p in primes]
    bounds = [bound_func(e) for e in exps]
    
    for combo in iterproduct(*[range(b + 1) for b in bounds]):
        res = 1
        for p, a in zip(primes, combo):
            res = (res * pow(p, a, A)) % A
        if res == target_res % A:
            return dict(zip(primes, combo))
    return None


def find_shortest_signed_representation(dlog_coords, exponents, h, target):
    """Find the minimum number of nonzero δ_i values needed to represent
    target as Σ s_i*δ_i mod h with -e_i ≤ δ_i ≤ e_i.
    
    Try 1, 2, 3 nonzero terms first, then full search.
    Returns (length, {p_index: delta_i}) or (None, None) if not found.
    """
    k = len(dlog_coords)
    target = target % h
    
    # Try 0 terms (target = 0)
    if target == 0:
        return 0, {}
    
    # Try 1 nonzero term: s_i * δ_i ≡ target (mod h)
    for i in range(k):
        s_i = dlog_coords[i]
        for delta in range(-exponents[i], exponents[i] + 1):
            if delta == 0:
                continue
            if (delta * s_i) % h == target:
                return 1, {i: delta}
    
    # Try 2 nonzero terms
    for i in range(k):
        for j in range(i + 1, k):
            for delta_i in range(-exponents[i], exponents[i] + 1):
                if delta_i == 0:
                    continue
                remain = (target - delta_i * dlog_coords[i]) % h
                for delta_j in range(-exponents[j], exponents[j] + 1):
                    if delta_j == 0:
                        continue
                    if (delta_j * dlog_coords[j]) % h == remain:
                        return 2, {i: delta_i, j: delta_j}
    
    # Try 3 nonzero terms
    for i in range(k):
        for j in range(i + 1, k):
            for l in range(j + 1, k):
                for delta_i in range(-exponents[i], exponents[i] + 1):
                    if delta_i == 0:
                        continue
                    remain1 = (target - delta_i * dlog_coords[i]) % h
                    for delta_j in range(-exponents[j], exponents[j] + 1):
                        if delta_j == 0:
                            continue
                        remain2 = (remain1 - delta_j * dlog_coords[j]) % h
                        for delta_l in range(-exponents[l], exponents[l] + 1):
                            if delta_l == 0:
                                continue
                            if (delta_l * dlog_coords[l]) % h == remain2:
                                return 3, {i: delta_i, j: delta_j, l: delta_l}
    
    # Full search using the centered sumset
    sigma = compute_centered_sumset(dlog_coords, exponents, h)
    if target in sigma:
        # Find any representation via brute force over all combinations
        ranges = [range(-e, e + 1) for e in exponents]
        for combo in iterproduct(*ranges):
            val = sum(d * s for d, s in zip(combo, dlog_coords)) % h
            if val == target:
                nonzero = {i: d for i, d in enumerate(combo) if d != 0}
                return len(nonzero), nonzero
    
    return None, None


# ── Main analysis ───────────────────────────────────────────────────────────

def main():
    max_n = 100000
    A_values = [3, 7, 11, 19, 23, 31]
    
    print(f"Centered Divisor-Residue Set Analysis")
    print(f"  n range: 13 to {max_n}")
    print(f"  A values: {A_values}")
    print(f"  Conditions: n prime, n ≡ 1 (mod 12), n ≢ 0 (mod 5), gcd(n,A)=1")
    print()
    
    results = []
    failure_delta_details = []  # Details for the 821 failure cases
    
    # Statistics
    total_cases = 0
    criterion_match_count = 0
    criterion_mismatch_count = 0
    h_half_in_sigma_count = 0
    T_in_DA_count = 0
    route_type_dist = Counter()
    shortest_len_dist = Counter()
    failure_h_half_in_sigma = 0
    failure_count = 0
    
    for n in range(13, max_n + 1):
        if n % 12 != 1 or n % 5 == 0:
            continue
        if not isprime(n):
            continue
        
        for A in A_values:
            if gcd(n, A) > 1:
                continue
            
            # Compute N = n*(n+A)/4
            m = (n + A) // 4
            N = n * m  # This is nx = n * (n+A)/4
            N_factors = factorint(N)
            
            # Compute H(A)
            H = compute_H_A_from_factors(N_factors, A)
            h = len(H)
            
            # Skip if H is trivial (shouldn't happen for our primes but guard)
            if h == 0:
                continue
            
            # Check if -1 ∈ H(A)
            neg1 = A - 1
            neg1_in_H = neg1 in H
            
            # Compute T = -N mod A
            T = (-N) % A
            
            # Compute D_A(N²) with bound 2*e_i
            D_A = compute_D_A(n, A, N_factors)
            T_in_DA = T in D_A
            neg1_in_DA = neg1 in D_A
            
            # Find generator u of H(A) and build dlog table
            u = subgroup_generator(A, H)
            dlog = dlog_table(A, u, h)
            
            # Compute dlog coordinates s_i for each prime factor
            prime_factors = [p for p in N_factors if gcd(p, A) == 1]
            exponents = [N_factors[p] for p in prime_factors]
            dlog_coords = [dlog[p % A] for p in prime_factors]
            
            # Compute centered sumset Σ_A(N)
            sigma = compute_centered_sumset(dlog_coords, exponents, h)
            
            # Check h/2 ∈ Σ_A(N)
            if h % 2 == 0:
                h_half = h // 2
                h_half_in_sigma = h_half in sigma
            else:
                h_half = None
                h_half_in_sigma = False
            
            # Check criterion match
            criterion_match = (h_half_in_sigma == T_in_DA) if h_half is not None else (not T_in_DA and not h_half_in_sigma)
            
            total_cases += 1
            if criterion_match:
                criterion_match_count += 1
            else:
                criterion_mismatch_count += 1
            
            if h_half_in_sigma:
                h_half_in_sigma_count += 1
            if T_in_DA:
                T_in_DA_count += 1
            
            # Compute stabilizer (additive stabilizer in Z/hZ of the centered sumset)
            if h > 0:
                stab = compute_stabilizer(sigma, h)
                stabilizer_size = len(stab)
            else:
                stabilizer_size = 0
            
            # Find shortest signed representation of h/2
            shortest_len = None
            signed_repr = None
            if h_half is not None and h_half_in_sigma:
                shortest_len, signed_repr = find_shortest_signed_representation(
                    dlog_coords, exponents, h, h_half
                )
            
            # Classify route type
            route_type = classify_route_type(
                h, dlog_coords, exponents, h_half, h_half_in_sigma,
                T_in_DA, neg1_in_H, neg1_in_DA, stabilizer_size,
                shortest_len
            )
            route_type_dist[route_type] += 1
            if shortest_len is not None:
                shortest_len_dist[shortest_len] += 1
            
            # Build entry
            entry = {
                "n": n,
                "A": A,
                "h": h,
                "N": N,
                "factorization": {str(p): e for p, e in N_factors.items()},
                "dlog_vector": {str(p): dlog[p % A] for p in prime_factors},
                "h_half_in_sigma": h_half_in_sigma,
                "T_in_DA": T_in_DA,
                "criterion_match": criterion_match,
                "shortest_signed_length": shortest_len,
                "signed_representation": {str(prime_factors[i]): delta for i, delta in signed_repr.items()} if signed_repr else None,
                "route_type": route_type,
                "stabilizer_size": stabilizer_size,
            }
            results.append(entry)
            
            # For failure cases (where -1 ∉ D_A, i.e., the 821 cases)
            if neg1_in_H and not neg1_in_DA:
                failure_count += 1
                # Compute the working divisor P for T ∈ D_A
                T_witness = find_witness_for_residue(N_factors, A, T, lambda e: 2 * e)
                # Compute δ_i = α_i - e_i
                if T_witness:
                    delta_info = {}
                    for p in prime_factors:
                        e_i = N_factors[p]
                        alpha_i = T_witness.get(p, 0)
                        delta_i = alpha_i - e_i
                        delta_info[str(p)] = {
                            "e_i": e_i,
                            "alpha_i": alpha_i,
                            "delta_i": delta_i,
                            "s_i": dlog[p % A],
                        }
                    
                    # Check if h/2 is in the centered set for this failure case
                    if h_half_in_sigma:
                        failure_h_half_in_sigma += 1
                    
                    failure_delta_details.append({
                        "n": n,
                        "A": A,
                        "h": h,
                        "N": N,
                        "T": T,
                        "neg1_in_H": True,
                        "neg1_in_DA": False,
                        "T_in_DA": T_in_DA,
                        "h_half_in_sigma": h_half_in_sigma,
                        "T_witness": {str(p): a for p, a in T_witness.items()},
                        "delta_info": delta_info,
                    })
    
    # ── Output ────────────────────────────────────────────────────────────
    
    print(f"\n{'='*70}")
    print(f"SUMMARY STATISTICS")
    print(f"{'='*70}")
    print(f"Total cases: {total_cases}")
    print(f"Criterion match (T ∈ D_A iff h/2 ∈ Σ_A): {criterion_match_count} ({100*criterion_match_count/total_cases:.2f}%)")
    print(f"Criterion mismatches: {criterion_mismatch_count}")
    print(f"h/2 ∈ Σ_A(N): {h_half_in_sigma_count}")
    print(f"T ∈ D_A: {T_in_DA_count}")
    print()
    print(f"Route type distribution:")
    for rt, cnt in sorted(route_type_dist.items(), key=lambda x: -x[1]):
        print(f"  {rt}: {cnt} ({100*cnt/total_cases:.2f}%)")
    print()
    print(f"Shortest signed length distribution:")
    for sl, cnt in sorted(shortest_len_dist.items()):
        print(f"  {sl}: {cnt}")
    print()
    print(f"Failure cases (where -1 ∉ D_A): {failure_count}")
    print(f"  Of which h/2 ∈ Σ_A(N) (centered set works): {failure_h_half_in_sigma}")
    print(f"  Of which h/2 ∉ Σ_A(N) (true failures): {failure_count - failure_h_half_in_sigma}")
    
    # Build output JSON
    output = {
        "description": "Centered divisor-residue set analysis for Erdős–Straus lemma",
        "parameters": {
            "max_n": max_n,
            "A_values": A_values,
            "conditions": "n prime, n ≡ 1 (mod 12), n ≢ 0 (mod 5), gcd(n,A)=1",
        },
        "summary": {
            "total_cases": total_cases,
            "criterion_match": criterion_match_count,
            "criterion_mismatch": criterion_mismatch_count,
            "match_pct": round(100 * criterion_match_count / max(1, total_cases), 4),
            "h_half_in_sigma": h_half_in_sigma_count,
            "T_in_DA": T_in_DA_count,
            "route_type_distribution": dict(route_type_dist),
            "shortest_signed_length_distribution": dict(shortest_len_dist),
            "failure_count": failure_count,
            "failure_h_half_in_sigma": failure_h_half_in_sigma,
            "failure_true_failures": failure_count - failure_h_half_in_sigma,
        },
        "failure_delta_details": failure_delta_details,
        "cases": results,
    }
    
    out_json = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'centered_residue_analysis.json')
    with open(out_json, 'w') as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\nJSON written to {out_json}")
    print(f"  Total entries: {len(results)}")
    print(f"  Failure detail entries: {len(failure_delta_details)}")


def classify_route_type(h, dlog_coords, exponents, h_half, h_half_in_sigma,
                        T_in_DA, neg1_in_H, neg1_in_DA, stabilizer_size,
                        shortest_len):
    """Classify a case into one of the route types."""
    
    if not T_in_DA and not h_half_in_sigma:
        # Check if it's a failure where -1 ∈ H but neither criterion holds
        if neg1_in_H and not neg1_in_DA:
            return "failure"
        # Otherwise it's just a case where neither applies (maybe -1 ∉ H)
        return "failure"
    
    # Check order-2: some s_i = h/2
    if h_half is not None:
        for s_i in dlog_coords:
            if s_i == h_half:
                return "order-2"
    
    # Check short-signed: ≤3 nonzero terms
    if shortest_len is not None and shortest_len <= 3:
        return "short-signed"
    
    # Check centered-Kneser: trivial stabilizer + size condition
    if stabilizer_size == 1:
        # Check size condition: Σ(2*e_i + 1) ≥ h/2 + k - 1
        k = len(dlog_coords)
        sum_range = sum(2 * e + 1 for e in exponents)
        kneser_bound = h_half + k - 1 if h_half is not None else 0
        if sum_range >= kneser_bound:
            return "centered-kneser"
    
    # If it works but doesn't fit above categories
    if T_in_DA or h_half_in_sigma:
        return "computational-only"
    
    return "failure"


if __name__ == "__main__":
    main()