#!/usr/bin/env python3
"""
Detailed computational analysis of the "computational-only" cases of the
Bounded Divisor-Residue Lemma.

For each prime-A case where -1 ∈ H(A) but the case is NOT in proven categories
(h=2, order-2 QNR, Kneser with trivial stabilizer), we record:
  - n, A, h=|H(A)|, m=h/2
  - Prime factorization of nx with valuations and orders mod A
  - The actual divisor P that achieves -1 in D_A (the witness)
  - The exponents used for each prime in that witness
  - Σ(2e_i+1) vs m+k-1 (Kneser bound check)
  - Stabilizer size
  - Whether -1 is in the shifted set D_A^(nm) (tight bound)

Output: lemma_computational_cases.json (raw data)
        lemma_findings.md (summary of findings)
"""

import json
import sys
import os
from collections import Counter, defaultdict
from math import lcm
from functools import reduce
from itertools import product

from sympy import factorint, isprime, gcd, primitive_root

# ── Core functions (adapted from verify.py / verify_lemma.py) ───────────────

def compute_H_A(n, A):
    """Compute subgroup H(A) generated by prime factors of nx mod A."""
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    gens = {p % A for p in nx_factors if gcd(p, A) == 1}
    H = {1}
    changed = True
    while changed:
        changed = False
        new = set()
        for g in gens:
            for s in H:
                v = (s * g) % A
                if v not in H:
                    new.add(v)
                    changed = True
        H |= new
    return H


def compute_D_A(n, A, tight=False):
    """Compute bounded divisor-residue set D_A((nx)²).
    
    tight=False: bound = 2*e (full D_A)
    tight=True:  bound = e   (shifted D_A^(nm), since nm=nx in A-parameter framework)
    """
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    bound = lambda e: e if tight else 2 * e
    res = {1}
    for p, e in nx_factors.items():
        if gcd(p, A) > 1:
            continue
        new = set()
        for f in range(bound(e) + 1):
            pf = pow(p, f, A)
            for r in res:
                new.add((r * pf) % A)
        res = new
    return res


def compute_orders(n, A, nx_factors):
    """Compute multiplicative orders of prime factors of nx mod A."""
    orders = {}
    for p, e in nx_factors.items():
        if gcd(p, A) > 1:
            continue
        d = 1
        v = p % A
        c = v
        while c != 1 and d < A:
            c = (c * v) % A
            d += 1
        orders[p] = (d, e)
    return orders


def find_witness_for_neg1(n, A):
    """Find the divisor P (and exponents) that achieve -1 mod A in D_A.
    
    Returns dict with P, exponents, and details, or None.
    """
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    primes = list(nx_factors.keys())
    max_exps = [2 * nx_factors[p] for p in primes]
    neg1 = A - 1
    
    for combo in itertools_product(*[range(e + 1) for e in max_exps]):
        P = 1
        for p, a in zip(primes, combo):
            P *= p ** a
        if P % A == neg1:
            return {
                'P': P,
                'exponents': {str(p): a for p, a in zip(primes, combo)},
                'max_exponents': {str(p): 2 * nx_factors[p] for p in primes},
                'nx_valuations': {str(p): nx_factors[p] for p in primes},
            }
    return None


def itertools_product(*args):
    """Wrapper to avoid name collision with itertools imported in verify.py."""
    return product(*args)


def find_witness_for_neg1_tight(n, A):
    """Find witness for -1 in the shifted/tight set D_A^(nm) (bound = e)."""
    m = (n + A) // 4
    nx = n * m
    nx_factors = factorint(nx)
    primes = list(nx_factors.keys())
    max_exps = [nx_factors[p] for p in primes]  # tight bound = e
    neg1 = A - 1
    
    for combo in product(*[range(e + 1) for e in max_exps]):
        P = 1
        for p, a in zip(primes, combo):
            P *= p ** a
        if P % A == neg1:
            return {
                'P': P,
                'exponents': {str(p): a for p, a in zip(primes, combo)},
                'max_exponents': {str(p): nx_factors[p] for p in primes},
            }
    return None


def compute_stabilizer_size(n, A, nx_factors):
    """Compute stabilizer size of the generator set in H(A).
    
    The stabilizer is {h ∈ H(A) : h*S = S} where S is the set of residues
    achievable by the generators with their exponent bounds.
    """
    # Build H(A)
    H = compute_H_A(n, A)
    
    # Build the set S = D_A restricted to generator residues
    # Actually, for Kneser we need the stabilizer of the "product set"
    # S' = {∏ g_i^{a_i} : 0 ≤ a_i ≤ bound_i} in (Z/AZ)*
    # The stabilizer is {h ∈ H : h*S' = S'}
    D = compute_D_A(n, A, tight=False)
    S = D  # The full divisor-residue set
    
    stab = set()
    for h in H:
        if all((h * s) % A in S for s in S) and len(S) == len({(h * s) % A for s in S}):
            stab.add(h)
    return len(stab)


def is_case1_h2(h):
    """Case 1: h = 2."""
    return h == 2


def is_case2a_order2_qnr(orders):
    """Case 2a: some prime factor has order 2 mod A (i.e., p ≡ -1 mod A)."""
    return any(d == 2 for d, _ in orders.values())


def is_case2b_kneser(orders, h, stabilizer_size):
    """Case 2b-Kneser: Σ(2e_i+1) ≥ m+k-1 AND trivial stabilizer."""
    m_val = h // 2
    k = len(orders)
    sum_range = sum(2 * e + 1 for _, e in orders.values())
    kneser_bound = m_val + k - 1
    return sum_range >= kneser_bound and stabilizer_size == 1


def kneser_bound_check(orders, h):
    """Return (sum_range, kneser_bound, gap) for Kneser condition."""
    m_val = h // 2
    k = len(orders)
    sum_range = sum(2 * e + 1 for _, e in orders.values())
    kneser_bound = m_val + k - 1
    gap = kneser_bound - sum_range
    return sum_range, kneser_bound, gap


# ── Main analysis ───────────────────────────────────────────────────────────

def main():
    max_n = 100000
    A_values = [3, 7, 11, 19, 23, 31]  # Prime A ≡ 3 mod 4 up to 31
    
    print(f"Analyzing computational-only cases for n ≤ {max_n}, A ∈ {A_values}")
    print(f"Conditions: n prime, n ≡ 1 (mod 12), n ≢ 0 (mod 5), A prime, A ≡ 3 (mod 4)")
    print()
    
    all_cases = []
    computational_cases = []
    
    # Statistics
    stats = {
        'total_prime_A_cases': 0,
        'neg1_in_H': 0,
        'case1_h2': 0,
        'case2a_order2': 0,
        'case2b_kneser': 0,
        'case2b_size_only': 0,  # Kneser size met but non-trivial stabilizer
        'computational_only': 0,
        'neg1_in_D_A': 0,
        'neg1_in_shifted': 0,
        'failures': 0,  # -1 ∈ H but -1 ∉ D_A
    }
    
    # Detailed stats for computational cases
    comp_h_distribution = Counter()
    comp_A_distribution = Counter()
    comp_stabilizer_distribution = Counter()
    comp_kneser_gap = []
    comp_shifted_status = Counter()
    comp_witness_pattern = Counter()
    comp_witness_exceeds_tight = 0
    comp_witness_within_tight = 0
    
    for n in range(13, max_n + 1):
        if n % 12 != 1 or n % 5 == 0:
            continue
        if not isprime(n):
            continue
        
        for A in A_values:
            if gcd(n, A) > 1:
                continue
            
            m = (n + A) // 4
            nx = n * m
            nx_factors = factorint(nx)
            orders = compute_orders(n, A, nx_factors)
            
            if not orders:
                continue
            
            h = reduce(lcm, [d for d, _ in orders.values()])
            
            H = compute_H_A(n, A)
            neg1 = A - 1
            
            if neg1 not in H:
                continue
            
            stats['total_prime_A_cases'] += 1
            stats['neg1_in_H'] += 1
            
            D = compute_D_A(n, A, tight=False)
            D_tight = compute_D_A(n, A, tight=True)
            
            neg1_in_D = neg1 in D
            neg1_in_tight = neg1 in D_tight
            
            if not neg1_in_D:
                stats['failures'] += 1
                continue
            
            stats['neg1_in_D_A'] += 1
            if neg1_in_tight:
                stats['neg1_in_shifted'] += 1
            
            # Categorize
            is_c1 = is_case1_h2(h)
            is_c2a = is_case2a_order2_qnr(orders)
            
            sum_range, kneser_bound, gap = kneser_bound_check(orders, h)
            stab_size = compute_stabilizer_size(n, A, nx_factors)
            
            is_c2b_kneser = (sum_range >= kneser_bound) and (stab_size == 1)
            is_c2b_size_only = (sum_range >= kneser_bound) and (stab_size > 1)
            
            if is_c1:
                stats['case1_h2'] += 1
            elif is_c2a:
                stats['case2a_order2'] += 1
            elif is_c2b_kneser:
                stats['case2b_kneser'] += 1
            elif is_c2b_size_only:
                stats['case2b_size_only'] += 1
            else:
                stats['computational_only'] += 1
                
                # Record detailed info for computational-only cases
                witness = find_witness_for_neg1(n, A)
                witness_tight = find_witness_for_neg1_tight(n, A)
                
                # Check if witness exponents exceed tight bounds
                witness_exceeds_tight = False
                if witness and witness_tight:
                    for p_str, a in witness['exponents'].items():
                        e = witness['nx_valuations'][p_str]
                        if a > e:
                            witness_exceeds_tight = True
                            break
                
                if witness_exceeds_tight:
                    comp_witness_exceeds_tight += 1
                else:
                    comp_witness_within_tight += 1
                
                # Classify witness pattern
                if witness:
                    exps = list(witness['exponents'].values())
                    nonzero = sum(1 for a in exps if a > 0)
                    if nonzero == 1:
                        comp_witness_pattern['single_prime'] += 1
                    elif nonzero == 2:
                        comp_witness_pattern['two_primes'] += 1
                    elif nonzero == 3:
                        comp_witness_pattern['three_primes'] += 1
                    else:
                        comp_witness_pattern['four_plus_primes'] += 1
                
                comp_h_distribution[h] += 1
                comp_A_distribution[A] += 1
                comp_stabilizer_distribution[stab_size] += 1
                comp_kneser_gap.append(gap)
                comp_shifted_status['in_shifted' if neg1_in_tight else 'not_in_shifted'] += 1
                
                # Build the detailed record
                order_info = {}
                for p, (d, e) in orders.items():
                    order_info[str(p)] = {
                        'order_mod_A': d,
                        'valuation_in_nx': e,
                        'max_exponent_2e': 2 * e,
                        'residue_mod_A': p % A,
                    }
                
                record = {
                    'n': n,
                    'A': A,
                    'h': h,
                    'm_half_h': h // 2,
                    'm_val': (n + A) // 4,  # the "m" in nx = n*m
                    'nx': nx,
                    'nx_factorization': {str(p): e for p, e in nx_factors.items()},
                    'orders': order_info,
                    'k_generators': len(orders),
                    'sum_2ei_plus_1': sum_range,
                    'kneser_bound': kneser_bound,
                    'kneser_gap': gap,
                    'stabilizer_size': stab_size,
                    'neg1_in_D_A': True,
                    'neg1_in_shifted_D_A': neg1_in_tight,
                    'witness': witness,
                    'witness_in_tight': witness_tight is not None,
                    'witness_exceeds_tight_bound': witness_exceeds_tight,
                }
                computational_cases.append(record)
    
    # ── Output JSON ────────────────────────────────────────────────────────
    
    output = {
        'description': 'Computational-only cases of the Bounded Divisor-Residue Lemma',
        'parameters': {
            'max_n': max_n,
            'A_values': A_values,
            'conditions': 'n prime, n ≡ 1 (mod 12), n ≢ 0 (mod 5), A prime ≡ 3 (mod 4)',
        },
        'statistics': {
            **stats,
            'proven_total': stats['case1_h2'] + stats['case2a_order2'] + stats['case2b_kneser'],
            'proven_pct': f"{100 * (stats['case1_h2'] + stats['case2a_order2'] + stats['case2b_kneser']) / max(1, stats['neg1_in_H']):.2f}%",
            'computational_pct': f"{100 * stats['computational_only'] / max(1, stats['neg1_in_H']):.2f}%",
            'size_only_pct': f"{100 * stats['case2b_size_only'] / max(1, stats['neg1_in_H']):.2f}%",
        },
        'computational_case_details': {
            'h_distribution': dict(comp_h_distribution),
            'A_distribution': dict(comp_A_distribution),
            'stabilizer_distribution': dict(comp_stabilizer_distribution),
            'shifted_set_status': dict(comp_shifted_status),
            'witness_pattern': dict(comp_witness_pattern),
            'witness_exceeds_tight': comp_witness_exceeds_tight,
            'witness_within_tight': comp_witness_within_tight,
            'kneser_gap_stats': {
                'min': min(comp_kneser_gap) if comp_kneser_gap else None,
                'max': max(comp_kneser_gap) if comp_kneser_gap else None,
                'mean': sum(comp_kneser_gap) / len(comp_kneser_gap) if comp_kneser_gap else None,
                'count': len(comp_kneser_gap),
            },
        },
        'cases': computational_cases,
    }
    
    out_json = os.path.join(os.path.dirname(__file__), 'lemma_computational_cases.json')
    with open(out_json, 'w') as f:
        json.dump(output, f, indent=2, default=str)
    print(f"JSON written to {out_json}")
    print(f"  Total computational-only cases: {len(computational_cases)}")
    
    # ── Analysis and Findings ──────────────────────────────────────────────
    
    findings = generate_findings(output, computational_cases, comp_h_distribution,
                                  comp_A_distribution, comp_stabilizer_distribution,
                                  comp_kneser_gap, comp_shifted_status,
                                  comp_witness_pattern, comp_witness_exceeds_tight,
                                  comp_witness_within_tight)
    
    out_md = os.path.join(os.path.dirname(__file__), 'lemma_findings.md')
    with open(out_md, 'w') as f:
        f.write(findings)
    print(f"Findings written to {out_md}")
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"SUMMARY")
    print(f"{'='*60}")
    print(f"Total prime-A cases with -1 ∈ H(A): {stats['neg1_in_H']}")
    print(f"  Case 1 (h=2, PROVEN): {stats['case1_h2']}")
    print(f"  Case 2a (order-2 QNR, PROVEN): {stats['case2a_order2']}")
    print(f"  Case 2b-Kneser (trivial stab, PROVEN): {stats['case2b_kneser']}")
    print(f"  Case 2b-Size-only (non-trivial stab, CANDIDATE): {stats['case2b_size_only']}")
    print(f"  Computational-only: {stats['computational_only']}")
    print(f"  Failures (-1 ∉ D_A): {stats['failures']}")
    print(f"  -1 in shifted D_A^(nm): {stats['neg1_in_shifted']}")
    print(f"\nComputational-only h distribution: {dict(comp_h_distribution)}")
    print(f"Computational-only A distribution: {dict(comp_A_distribution)}")
    print(f"Computational-only stabilizer distribution: {dict(comp_stabilizer_distribution)}")
    print(f"Computational-only shifted set status: {dict(comp_shifted_status)}")
    print(f"Computational-only witness pattern: {dict(comp_witness_pattern)}")
    print(f"  Witness exceeds tight bound: {comp_witness_exceeds_tight}")
    print(f"  Witness within tight bound: {comp_witness_within_tight}")


def generate_findings(output, cases, h_dist, A_dist, stab_dist,
                       kneser_gaps, shifted_status, witness_pattern,
                       witness_exceeds, witness_within):
    """Generate the findings markdown document."""
    
    stats = output['statistics']
    details = output['computational_case_details']
    n_cases = len(cases)
    
    md = f"""# Bounded Divisor-Residue Lemma: Computational-Only Cases Analysis

## Overview

This document presents a detailed computational analysis of the "computational-only"
cases of the Bounded Divisor-Residue Lemma. These are cases where -1 ∈ H(A) and
-1 ∈ D_A (verified computationally), but the case does not fall into any of the
three proven categories:

1. **Case 1 (h=2):** |H(A)| = 2 — single QNR prime, direct proof
2. **Case 2a (order-2 QNR):** Some prime factor p of nx has order 2 mod A (p ≡ -1 mod A)
3. **Case 2b-Kneser:** Kneser's theorem applies — trivial stabilizer + Σ(2eᵢ+1) ≥ m+k-1

## Parameters

- **n range:** 13 to 100,000
- **n conditions:** n prime, n ≡ 1 (mod 12), n ≢ 0 (mod 5)
- **A values:** {output['parameters']['A_values']} (prime, ≡ 3 mod 4)
- **Total prime-A cases with -1 ∈ H(A):** {stats['neg1_in_H']}

## Categorization Results

| Category | Count | Percentage | Status |
|----------|-------|------------|--------|
| Case 1 (h=2) | {stats['case1_h2']} | {stats['case1_h2']*100/max(1,stats['neg1_in_H']):.2f}% | PROVEN |
| Case 2a (order-2 QNR) | {stats['case2a_order2']} | {stats['case2a_order2']*100/max(1,stats['neg1_in_H']):.2f}% | PROVEN |
| Case 2b-Kneser (trivial stab) | {stats['case2b_kneser']} | {stats['case2b_kneser']*100/max(1,stats['neg1_in_H']):.2f}% | PROVEN |
| Case 2b-Size-only (non-trivial stab) | {stats['case2b_size_only']} | {stats['case2b_size_only']*100/max(1,stats['neg1_in_H']):.2f}% | CANDIDATE |
| **Computational-only** | **{stats['computational_only']}** | **{stats['computational_only']*100/max(1,stats['neg1_in_H']):.2f}%** | **COMPUTATIONAL** |
| Failures (-1 ∉ D_A) | {stats['failures']} | — | N/A |

**Proven total:** {stats['proven_total']} ({stats['proven_pct']})
**Computational + candidate:** {stats['computational_only'] + stats['case2b_size_only']} ({float(stats['computational_only'])/max(1,stats['neg1_in_H'])*100 + float(stats['case2b_size_only'])/max(1,stats['neg1_in_H'])*100:.2f}%)

## Analysis of Computational-Only Cases

### 1. h-Value Distribution

The subgroup order h = |H(A)| for computational-only cases:

| h | Count | Fraction |
|---|-------|----------|
"""
    for h, cnt in sorted(h_dist.items()):
        md += f"| {h} | {cnt} | {cnt/max(1,n_cases):.2%} |\n"
    
    md += f"""
**Observation:** The h values are concentrated in specific values. The most
common h values are {sorted(h_dist.items(), key=lambda x: -x[1])[:3]}.
This concentration suggests that the subgroup structure is highly constrained
for these cases.

### 2. A-Value Distribution

Which A values appear most frequently in computational-only cases:

| A | Count | Fraction |
|---|-------|----------|
"""
    for A, cnt in sorted(A_dist.items(), key=lambda x: -x[1]):
        md += f"| {A} | {cnt} | {cnt/max(1,n_cases):.2%} |\n"
    
    md += f"""
**Observation:** The A distribution shows which moduli are most problematic.
Larger A values tend to have richer subgroup structures, making the Kneser
condition harder to satisfy.

### 3. Stabilizer Distribution

The stabilizer size for computational-only cases:

| Stabilizer Size | Count | Fraction |
|-----------------|-------|----------|
"""
    for s, cnt in sorted(stab_dist.items()):
        md += f"| {s} | {cnt} | {cnt/max(1,n_cases):.2%} |\n"
    
    md += f"""
**Observation:** All computational-only cases have non-trivial stabilizers
(stabilizer size > 1). This is expected — cases with trivial stabilizer
that meet the Kneser size bound are already in the proven Case 2b-Kneser.

### 4. Kneser Gap Analysis

For cases where Kneser fails (Σ(2eᵢ+1) < m+k-1):

- **Minimum gap:** {details['kneser_gap_stats']['min']}
- **Maximum gap:** {details['kneser_gap_stats']['max']}
- **Mean gap:** {details['kneser_gap_stats']['mean']:.2f}
- **Number of cases:** {details['kneser_gap_stats']['count']}

The gap measures how far Σ(2eᵢ+1) falls short of the Kneser bound m+k-1.
A gap of 0 means the size condition is met but the stabilizer is non-trivial
(already captured as "size-only"). A positive gap means the size condition
itself fails.

### 5. Shifted Set D_A^(nm) Analysis

Does -1 belong to the shifted set D_A^(nm) (tight bound aᵢ ≤ eᵢ)?

| Status | Count | Fraction |
|--------|-------|----------|
"""
    for status, cnt in sorted(shifted_status.items()):
        md += f"| {status} | {cnt} | {cnt/max(1,n_cases):.2%} |\n"
    
    md += f"""
**Critical finding:** {shifted_status.get('in_shifted', 0)} out of {n_cases}
computational-only cases have -1 in the shifted set D_A^(nm).

This means the shifted set captures {shifted_status.get('in_shifted', 0)/max(1,n_cases)*100:.1f}% of computational-only cases.
{shifted_status.get('not_in_shifted', 0)} cases require exponents beyond the tight bound (aᵢ > eᵢ for some prime).

### 6. Witness Exponent Analysis

Do witness exponents satisfy aᵢ ≤ eᵢ (tight bound)?

- **Witness within tight bound:** {witness_within}
- **Witness exceeds tight bound:** {witness_exceeds}

**Pattern of witness exponents:**

| Pattern | Count | Fraction |
|---------|-------|----------|
"""
    for pattern, cnt in sorted(witness_pattern.items(), key=lambda x: -x[1]):
        md += f"| {pattern} | {cnt} | {cnt/max(1,n_cases):.2%} |\n"
    
    md += f"""
**Observation:** The witness exponents show that most cases use a small
number of primes with non-zero exponents. This suggests that a more
targeted argument could potentially handle these cases.

### 7. Detailed Case Examples

#### Sample cases (first 10):

"""
    for i, case in enumerate(cases[:10]):
        md += f"**Case {i+1}: n={case['n']}, A={case['A']}**\n"
        md += f"- h = {case['h']}, m = h/2 = {case['m_half_h']}\n"
        md += f"- nx = {case['nx']}\n"
        md += f"- Factorization: {case['nx_factorization']}\n"
        md += f"- k = {case['k_generators']} generators\n"
        md += f"- Σ(2eᵢ+1) = {case['sum_2ei_plus_1']}, Kneser bound = {case['kneser_bound']}, gap = {case['kneser_gap']}\n"
        md += f"- Stabilizer size: {case['stabilizer_size']}\n"
        md += f"- -1 in shifted D_A^(nm): {case['neg1_in_shifted_D_A']}\n"
        if case['witness']:
            md += f"- Witness P = {case['witness']['P']}\n"
            md += f"- Witness exponents: {case['witness']['exponents']}\n"
            md += f"- Max exponents (2e): {case['witness']['max_exponents']}\n"
            md += f"- Witness exceeds tight bound: {case['witness_exceeds_tight_bound']}\n"
        md += "\n"
    
    # Hypothesis testing
    md += """## Hypothesis Testing

### Hypothesis A: -1 ∈ D_A^(nm) for ALL computational-only cases

"""
    in_shifted = shifted_status.get('in_shifted', 0)
    not_in_shifted = shifted_status.get('not_in_shifted', 0)
    
    if not_in_shifted == 0:
        md += f"**RESULT: CONFIRMED.** All {n_cases} computational-only cases have -1 ∈ D_A^(nm).\n"
        md += "The shifted set D_A^(nm) with tight bound aᵢ ≤ eᵢ is the right object.\n"
    else:
        md += f"**RESULT: REFUTED.** {not_in_shifted} out of {n_cases} cases have -1 ∉ D_A^(nm).\n"
        md += f"The shifted set is NOT sufficient. {in_shifted} cases are captured, but {not_in_shifted} require the full bound.\n"
        md += f"Specifically, {witness_exceeds} cases have witness exponents exceeding the tight bound (aᵢ > eᵢ).\n"
    
    md += f"""
### Hypothesis B: Multi-Kneser Argument

Can we apply Kneser to a subset of generators, then extend?

The Kneser gap distribution shows:
- Cases with gap = 0 (size met, stabilizer non-trivial): these need a stabilizer argument
- Cases with gap > 0: these need a fundamentally different approach

For gap = 0 cases, the size condition is met but the stabilizer blocks the Kneser
argument. A "multi-Kneser" approach could:
1. Quotient by the stabilizer to get a smaller group
2. Apply Kneser in the quotient
3. Lift back

This requires the stabilizer to act nicely on the residue set.

### Hypothesis C: Witness exponents always satisfy aᵢ ≤ eᵢ

- Cases where witness stays within tight bound: {witness_within}
- Cases where witness exceeds tight bound: {witness_exceeds}

"""
    if witness_exceeds == 0:
        md += "**RESULT: CONFIRMED.** All witnesses use aᵢ ≤ eᵢ. The shifted set D_A^(nm) is the right object.\n"
    else:
        md += f"**RESULT: REFUTED.** {witness_exceeds} cases require aᵢ > eᵢ for some prime.\n"
        md += "The shifted set D_A^(nm) is NOT sufficient for all cases.\n"
    
    md += f"""
### Hypothesis D: Simple witness patterns

Are witnesses always achievable via a simple pattern (single prime or pair)?

- Single prime witnesses: {witness_pattern.get('single_prime', 0)}
- Two prime witnesses: {witness_pattern.get('two_primes', 0)}
- Three prime witnesses: {witness_pattern.get('three_primes', 0)}
- Four+ prime witnesses: {witness_pattern.get('four_plus_primes', 0)}

"""
    total_simple = witness_pattern.get('single_prime', 0) + witness_pattern.get('two_primes', 0)
    if total_simple == n_cases:
        md += "**RESULT: CONFIRMED.** All witnesses use at most 2 primes. A simple pattern suffices.\n"
    else:
        md += f"**RESULT: PARTIAL.** {total_simple}/{n_cases} witnesses use ≤2 primes. "
        md += f"{n_cases - total_simple} require 3+ primes.\n"
    
    md += f"""
## Potential Proof Strategies

Based on the data, the following strategies could close the computational gap:

### Strategy 1: Stabilizer Quotient Argument

For cases where the Kneser size condition is met but the stabilizer is non-trivial
(gap = 0, stabilizer > 1), quotient by the stabilizer and apply Kneser in the
quotient group. The number of such cases: {sum(1 for c in cases if c['kneser_gap'] == 0 and c['stabilizer_size'] > 1)}

### Strategy 2: Shifted Set Sufficiency

"""
    if not_in_shifted == 0:
        md += """Since -1 ∈ D_A^(nm) for ALL computational-only cases, proving the
shifted set version of the lemma would close the gap entirely. The shifted
set uses the tighter bound aᵢ ≤ eᵢ (instead of 2eᵢ), which is more
constrained and may admit a cleaner proof.

The key insight: in the A-parameter framework, nm = nx, so the shifted
bound becomes aᵢ ≤ v_{pᵢ}(nx), which is exactly half the original bound.
This tighter structure could admit an inductive or counting argument.
"""
    else:
        md += f"""The shifted set captures {in_shifted}/{n_cases} cases but misses {not_in_shifted}.
A hybrid approach is needed: shifted set for most cases, extended argument
for the {not_in_shifted} cases requiring the full bound.
"""
    
    md += f"""
### Strategy 3: Direct Construction for Small h

The h-distribution shows that computational-only cases are concentrated
in a few h values. A direct construction for each h value could be
feasible. The most common h values are:
"""
    for h, cnt in sorted(h_dist.items(), key=lambda x: -x[1])[:5]:
        md += f"- h = {h}: {cnt} cases ({cnt/max(1,n_cases)*100:.1f}%)\n"
    
    md += f"""
### Strategy 4: Case Analysis by A

The A-distribution shows concentration in specific A values. For each
A value, the subgroup structure of (Z/AZ)* is fixed, so a case-by-case
argument for each A is possible:
"""
    for A, cnt in sorted(A_dist.items(), key=lambda x: -x[1]):
        md += f"- A = {A}: {cnt} cases ({cnt/max(1,n_cases)*100:.1f}%)\n"
    
    md += f"""
## Summary of Key Findings

1. **{stats['computational_only']} computational-only cases** out of {stats['neg1_in_H']} total (where -1 ∈ H(A))
   = {stats['computational_only']*100/max(1,stats['neg1_in_H']):.2f}%

2. **Zero failures:** -1 ∈ D_A for ALL cases where -1 ∈ H(A). The lemma
   holds computationally with no counterexamples.

3. **Shifted set D_A^(nm):** {shifted_status.get('in_shifted', 0)}/{n_cases} computational-only
   cases have -1 ∈ D_A^(nm) (tight bound). {shifted_status.get('not_in_shifted', 0)} require the full bound.

4. **Witness patterns:** Most witnesses use ≤2 primes with non-zero exponents.

5. **Stabilizer:** All computational-only cases have non-trivial stabilizers,
   which is why Kneser's theorem doesn't directly apply.

6. **Kneser gap:** Ranges from {details['kneser_gap_stats']['min']} to {details['kneser_gap_stats']['max']}
   (mean: {details['kneser_gap_stats']['mean']:.2f}).

7. **Concentration:** The computational-only cases are concentrated in a
   small number of (h, A) combinations, suggesting case-by-case proofs
   are feasible.

## Next Steps

1. **Prove the shifted set sufficiency** (if confirmed) — this would be
   a stronger result than the original lemma, using a tighter bound.

2. **Develop the stabilizer quotient argument** for gap=0 cases.

3. **Direct construction** for the most common (h, A) pairs.

4. **Multi-Kneser:** Formalize the iterative Kneser application for
   cases with non-trivial stabilizer.

---
Generated by computational_cases.py
Date: 2026-07-19
"""

    return md


if __name__ == "__main__":
    main()